In [ ]:
#Numpy là viết tắt của Numerical Python - Thư viện mã nguồn mở trong python - tính toán số học

In [ ]:
#Cung cấp  - các cấu trúc dữ liệu và hàm để xử lý các phép toán làm việc với mảng và thực hiện tính toán số học

#Import module numpy

In [ ]:
import numpy as np

#Tạo 1 mảng dữ liệu

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
a.shape

(3,)

In [ ]:
a[0]

1

#Mảng 2 chiều

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b.shape

(2, 3)

In [ ]:
b[1,1]

5

#Tạo mảng ngẫu nhiên

In [ ]:
c = np.random.random((2,3))
c

array([[0.89359831, 0.59191313, 0.46067578],
       [0.38058403, 0.81381135, 0.26508647]])

In [ ]:
np.random.seed(11)
c=np.random.random((2,3))
c

array([[0.18026969, 0.01947524, 0.46321853],
       [0.72493393, 0.4202036 , 0.4854271 ]])

In [ ]:
d = np.array([[[1,2,3],
               [4,5,6]],
              
              [[7,8,9],
               [10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
d.shape

(2, 2, 3)

#Reshape

In [ ]:
e = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
e

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(e.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
f =  np.array([1,2,3,4,5,6,7,8,9])
f.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.reshape(6)

array([1, 2, 3, 4, 5, 6])

#So sánh trong numpy

In [ ]:
f>3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [ ]:
f[f>3]

array([4, 5, 6, 7, 8, 9])

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
g = np.array([[7,8,9],[10,11,12]])
g

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
b*g

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
b/g

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

#Tổng, Min, Max

In [ ]:
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
f.sum()

45

In [ ]:
f.min()

1

In [ ]:
f.max()

9

#Nhân ma trận

In [ ]:
A = np.array([[1,2],[2,1],[3,2],[4,5]])
A

array([[1, 2],
       [2, 1],
       [3, 2],
       [4, 5]])

In [ ]:
B= np.array([[3,2,1],[4,2,6]])
B

array([[3, 2, 1],
       [4, 2, 6]])

In [ ]:
C = A.dot(B)
C

array([[11,  6, 13],
       [10,  6,  8],
       [17, 10, 15],
       [32, 18, 34]])

Cài đặt module
Lấy danh sách tin mới nhất
Lấy dữ liệu tin tức chi tiết từng bài


In [ ]:
#cài đặt module requests
# pip install requests
#cài đặt module Pillow
# pip install Pillow

requests.mothod(get, post, put, delete...)

requests.get("bỏ địa chỉ cần lấy vào đây")

In [ ]:
import requests as rq

In [ ]:
r = rq.get("https://tuoitre.vn/tin-moi-nhat.htm")
print(r.content)

b'\r\n    <!DOCTYPE html>\r\n    <html id="mainHtml" lang="vi" xmlns="http://www.w3.org/1999/xhtml">\r\n    <head prefix="og:&#32;http://ogp.me/ns#&#32;fb:&#32;http://ogp.me/ns/fb#&#32;website:&#32;http://ogp.me/ns/website#"><link rel="dns-prefetch" href="https://cdn.tuoitre.vn" /><link rel="dns-prefetch" href="https://cdn1.tuoitre.vn" /><link rel="dns-prefetch" href="https://statictuoitre.mediacdn.vn" /><link rel="dns-prefetch" href="https://adservice.google.com" /><link rel="dns-prefetch" href="https://adservice.google.com.vn" /><link rel="dns-prefetch" href="https://www.googletagservices.com" /><link rel="dns-prefetch" href="https://partner.googleadservices.com" /><link rel="dns-prefetch" href="https://js.aiservice.vn" /><link rel="dns-prefetch" href="https://media1.admicro.vn" /><link rel="dns-prefetch" href="https://lg1.logging.admicro.vn" /><link rel="dns-prefetch" href="https://static.contineljs.com" /><link rel="dns-prefetch" href="https://contineljs.com" /><link rel="preconnec

In [ ]:
from bs4 import BeautifulSoup as bs
soup = bs(r.content,"html.parser")
print(soup)


<!DOCTYPE html>

<html id="mainHtml" lang="vi" xmlns="http://www.w3.org/1999/xhtml">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#"><link href="https://cdn.tuoitre.vn" rel="dns-prefetch"/><link href="https://cdn1.tuoitre.vn" rel="dns-prefetch"/><link href="https://statictuoitre.mediacdn.vn" rel="dns-prefetch"/><link href="https://adservice.google.com" rel="dns-prefetch"/><link href="https://adservice.google.com.vn" rel="dns-prefetch"/><link href="https://www.googletagservices.com" rel="dns-prefetch"/><link href="https://partner.googleadservices.com" rel="dns-prefetch"/><link href="https://js.aiservice.vn" rel="dns-prefetch"/><link href="https://media1.admicro.vn" rel="dns-prefetch"/><link href="https://lg1.logging.admicro.vn" rel="dns-prefetch"/><link href="https://static.contineljs.com" rel="dns-prefetch"/><link href="https://contineljs.com" rel="dns-prefetch"/><link href="https://www.googletagmanager.com" rel="preconnect"/><link href

In [ ]:
titles = soup.find_all('h3',class_="box-title-text")

In [ ]:
print(titles)

[<h3 class="box-title-text" data-comment="20230201161646786">
<a class="box-category-link-title" data-id="20230201161646786" data-linktype="newsdetail" data-newstype="0" data-objecttype="" data-type="0" href="/cac-dai-gia-premier-league-mua-sam-the-nao-trong-mua-dong-20230201161646786.htm" title="Các đại gia Premier League mua sắm thế nào trong mùa đông?">Các đại gia Premier League mua sắm thế nào trong mùa đông?</a>
</h3>, <h3 class="box-title-text" data-comment="20230201161202107">
<a class="box-category-link-title" data-id="20230201161202107" data-linktype="newsdetail" data-newstype="0" data-objecttype="" data-type="0" href="/me-ngoai-35-tuoi-bo-tren-45-tuoi-co-nguy-co-sinh-con-khuyet-tat-20230201161202107.htm" title="Mẹ ngoài 35 tuổi, bố trên 45 tuổi có nguy cơ sinh con khuyết tật">Mẹ ngoài 35 tuổi, bố trên 45 tuổi có nguy cơ sinh con khuyết tật</a>
</h3>, <h3 class="box-title-text" data-comment="20230201140050746">
<a class="box-category-link-title" data-id="20230201140050746" dat

In [ ]:
links = [link.find('a').attrs["href"] for link in titles]
print(links)

['/cac-dai-gia-premier-league-mua-sam-the-nao-trong-mua-dong-20230201161646786.htm', '/me-ngoai-35-tuoi-bo-tren-45-tuoi-co-nguy-co-sinh-con-khuyet-tat-20230201161202107.htm', '/dau-nam-quy-mao-2023-gia-gas-ban-le-tang-manh-20230201140050746.htm', '/dan-mang-trung-quoc-lo-ceo-tiktok-gap-nguy-hiem-tai-my-20230201115012606.htm', '/da-nang-canh-sat-dot-kich-vu-truong-new-phuong-dong-nhieu-dan-choi-ma-tuy-gay-canh-20230201160159709.htm', '/de-xuat-co-che-moi-lam-cac-du-an-bot-o-tp-hcm-20230201152557466.htm', '/el-pais-tay-ban-nha-gui-xe-tang-leopard-cho-ukraine-20230201150602434.htm', '/cong-an-phuong-co-duoc-dung-xe-xu-phat-vi-pham-giao-thong-khong-20230201151348022.htm', '/khach-di-choi-tet-qua-tan-son-nhat-tang-61-20230201155807154.htm', '/phat-dong-cuoc-thi-bao-ve-nen-tang-tu-tuong-cua-dang-lan-thu-3-20230201154618226.htm', '/mang-xa-hoi-snapchat-bao-lo-nang-20230201155225369.htm', '/xe-may-dien-honda-cub-e-sang-cua-ban-tai-viet-nam-nhieu-chi-tiet-hien-dai-20230201111822056.htm', '/den-

In [ ]:
for link in links:
  news = rq.get("http://tuoitre.vn"+link)
  soup = bs(news.content,"html.parser")
  title=soup.find("h1",class_="detail-title").text
  mota = soup.find("h2",class_="detail-sapo").text
  print(30*"*")
  print("Tiêu đề:",title)
  print("Mô tả:", mota)

ConnectionError: ignored